org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

MYAPP_RELEASE_STORE_FILE=mi-clave.jks
MYAPP_RELEASE_STORE_PASSWORD=123456
MYAPP_RELEASE_KEY_ALIAS=mi-alias
MYAPP_RELEASE_KEY_PASSWORD=123456

# Configuración de Firma Release
MYAPP_RELEASE_STORE_FILE=mi-clave.jks
MYAPP_RELEASE_STORE_PASSWORD=MaxiVende2026!
MYAPP_RELEASE_KEY_ALIAS=maxivende
MYAPP_RELEASE_KEY_PASSWORD=MaxiVende2026!
